### ISSUE TITLE
Install Error: "alsa/asoundlib.h: No such file or directory"

### ISSUE THREAD

**Issue by tmack8080** [ayoisaiah/focus#1]
terry@zeus:~$ go install github.com/ayoisaiah/focus/cmd/focus@latest
# github.com/hajimehoshi/oto
go/pkg/mod/github.com/hajimehoshi/oto@v0.3.1/driver_linux.go:23:10: fatal error: alsa/asoundlib.h: No such file or directory
   23 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
terry@zeus:~$

**Comment by nandalopes** [comment]
Hi, you will need `libasound2-dev` package to compile.

[From package README](https://github.com/hajimehoshi/oto#linux)

**Comment by ayoisaiah** [comment]
Thanks @nandalopes will add to the readme.

@tmack8080 Please install the required library.
