### ISSUE TITLE
Resume is broken

### ISSUE THREAD

**Issue by Blackbeing** [ayoisaiah/focus#14]
Been using focus without any problem so far. But today after hibernation in linux (arch linux), when I `focus resume` it resumed at 1 min. I assumed that's where I left off. But after the short break, the next session also resumes at 1 min.
![2023-03-29-185612](https://user-images.githubusercontent.com/112502631/228598346-f1bb7ed3-23da-4597-96bb-08e5500d6f8a.png)

**Comment by ayoisaiah** [comment]
Could you please share your database file so I can find the problem?

**Comment by Blackbeing** [comment]
[focus.zip](https://github.com/ayoisaiah/focus/files/11133318/focus.zip)

**Comment by ayoisaiah** [comment]
https://github.com/ayoisaiah/focus/commit/0c42a895c665d07ea4e9e8d205e35e45050bf038
