### ISSUE TITLE
[FR] Define how often to output the time left on the console

### ISSUE THREAD

**Issue by capybarahero** [ayoisaiah/focus#18]
Hi there, thanks for the great app.

As a suggestion, it would be great if there were an option to choose how often to print timeRemaining - for example, every 1s, 1m, 5m, etc. Seeing the time going down every second doesn't help my anxiety :)

**Comment by ayoisaiah** [comment]
@capybarahero Honestly, I don't think this will be done. You can run Focus in a background tab or window if you don't want to watch the countdown and rely on the notifications to know when a session is over.
