### ISSUE TITLE
ASCII art prompt to always show up

### ISSUE THREAD

**Issue by theDataFixer** [ayoisaiah/focus#19]
I was wondering if there could be an enhancement to give you an option in configuration of getting that "FOCUS" ASCII art to show up always when starting a new instance in terminal. Or maybe also to get short and long break msg to be in ASCCI?

**Comment by ayoisaiah** [comment]
@theDataFixer In the future, I may make it possible to customize the entire timer output. But it's honestly not something I will prioritize anytime soon
