### ISSUE TITLE
No newline after executing "stats" command.

### ISSUE THREAD

**Issue by Abdullah16M** [ayoisaiah/focus#2]
Tested on: Alacritty (v0.9.0), st (v0.8.4)

**Comment by ayoisaiah** [comment]
Can you provide a screenshot demonstrating the issue?

**Comment by Abdullah16M** [comment]
![file](https://user-images.githubusercontent.com/68733950/142950180-1607c199-eb6a-454f-8cc4-e191de47d360.png)
 
the command line propmt isn't placed on a newline, but at the end of the output.

**Comment by ayoisaiah** [comment]
Thanks for reporting this issue. I've fixed it in [this commit](https://github.com/ayoisaiah/focus/commit/bd8091d19a24eb8af06073a5f0084aadc12cdbe6). Will release a new version soon.
