### ISSUE TITLE
Timer updates not staying on single line within default terminal app on macOS

### ISSUE THREAD

**Issue by cwithmichael** [ayoisaiah/focus#21]
<img width="514" alt="Screenshot 2023-10-18 at 4 38 47 PM" src="https://github.com/ayoisaiah/focus/assets/1703143/b0313ef2-0e1a-4cc0-87ba-bdcb0b855432">

Adding a carriage return [here](https://github.com/ayoisaiah/focus/blob/master/timer/timer.go#L497) to prevent advancing to the next line seems to fix the issue.
`"\r🕒%s:%s",`

Cheers

**Comment by ayoisaiah** [comment]
@cwithmichael Thanks so much for reporting this! I don't have a Mac to test the change so I will take your word for it https://github.com/ayoisaiah/focus/commit/436e150a8cc8c9c336d0280f463c2771eecae208
