### ISSUE TITLE
Focus stats doesn't output anything

### ISSUE THREAD

**Issue by Soupxasy** [ayoisaiah/focus#37]
### Tick this box to confirm you have reviewed the above.

- [X] I've discovered a new issue with Focus.

### What version of Focus are you using?

focus v1.4.2

### How did you install Focus?

Arch AUR

### What operating system are you using Focus on?

Arch

### What is your Focus configuration?

auto_start_break: true
auto_start_work: false
break_sound: bell
dark_theme: true
long_break_duration: 20m
long_break_interval: 2
long_break_msg: Take a long break
notify: true
session_cmd: ""
short_break_duration: 20m
short_break_msg: Take a breather
sound: ""
sound_on_break: false
strict: false
work_duration: 40m
work_msg: Focus on your task
work_sound: loud_bell

### Describe your bug.

` focus stats `  doesn't output anything, just displays: `INFO  starting server on port: 1111`.

### What are the steps to reproduce the behavior?

Run `focus stats` with any options.

### What behaviour did you observe?

No Output.

### What is the expected behaviour?

The stats should have been outputed, as in the readme.

**Comment by ayoisaiah** [comment]
@Soupxasy Sorry, the docs are outdated. Please point your browser to localhost:1111 to view the stats once `focus stats` is run
