### ISSUE TITLE
One instance error when ```focus``` command is run

### ISSUE THREAD

**Issue by Plastikov** [ayoisaiah/focus#5]
I get an error message when I run the ```focus``` command.

This is the first time I am installing the program and running it.
![focus-error](https://user-images.githubusercontent.com/78403778/156883608-301042d1-0626-4d31-86de-a23ca1d97a4a.jpg)

**Comment by ayoisaiah** [comment]
@Plastikov That's super weird. Are you on macOS?

**Comment by Plastikov** [comment]
No bro. How can I help to solve the problem? @ayoisaiah

**Comment by ayoisaiah** [comment]
@Plastikov Are you still experiencing this issue?
