### ISSUE TITLE
flac music files do not play

### ISSUE THREAD

**Issue by foxsetpass** [ayoisaiah/focus#7]
I specified the flac file as config and started. However, an error was displayed.
ERROR flac.decoder.Seek: not yet implemented

I was able to play ogg and wav.
It says flac is supported in the documentation, but is it not?

**Comment by ayoisaiah** [comment]
Thanks for reporting this. I believe it worked with the Flac files I tested, but I will look into it

**Comment by ayoisaiah** [comment]
Sorry, I'm unable to reproduce this issue. Could you provide the specific Flac file that failed?
