### ISSUE TITLE
Necessary requirement

### ISSUE THREAD

**Issue by juba0x00** [ayoisaiah/focus#8]
## Add Notification Sound
- after the Pomodoro finish the notification appears without any sound, How would we notice this notification 
- Many times I don't notice the notification (because there is no sound) while my study flow, after a while I go to the terminal and find that the Pomodoro is finished and the break is about to finish

**Comment by ayoisaiah** [comment]
@juba0x00 Thanks for reporting this. This will be fixed  soon and included in the next release

**Comment by juba0x00** [comment]
@ayoisaiah 
I think #6 is an excellent alternative to my suggestion.
I tried to use  `--short-break-cmd =command` option, But it didn't work.
```bash
focus --short-break-cmd=beep 
Incorrect Usage. flag provided but not defined: -short-break-cmd
[REDACTED HELP MENU]
ERROR  flag provided but not defined: -short-break-cmd
```
How can I use It?

**Comment by ayoisaiah** [comment]
@juba0x00 I'll release a new version today with the necessary fixes.

**Comment by ayoisaiah** [comment]
@juba0x00 I've added this feature but still need to cleanup a few things before releasing. Could you please build from source to test it out?

You don't need to add any option, it should use the system notification sound automatically.

If you want to run arbitrary commands after a session, you can use the new `--session-cmd` option.

**Comment by juba0x00** [comment]
`--session-cmd` option is working properly, but there is no notification sound by default. 
I'll use `--session-cmd` option to play sound.

![Screenshot_20221128_105400](https://user-images.githubusercontent.com/73611543/204234887-bd43ba00-1d8f-4129-929d-c3939d6cbe06.png)

**Comment by ayoisaiah** [comment]
@juba0x00 Do you have notification sounds enabled in your system settings?
